# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TableViewTest3' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TableViewTest3
  pod 'Masonry'
  pod 'MJExtension'
  
  target 'TableViewTest3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
